export const PRIMARY_DELIVERY_FIXTURE = {
  owner: "mtamburrano",
  repository: "proofboard-demo-fixture",
  baselineRef: "590aa8a6d72c580f61fc1b19d33e9876bc0feb9b",
  baselineSha: "590aa8a6d72c580f61fc1b19d33e9876bc0feb9b",
  base: "main",
  head: "proofboard-verified-delivery",
} as const;

export const PRIMARY_VERIFIED_DELIVERY_FILES = {
  "src/index.ts": [
    "export const productName = \"TrueForge Proof Board\" as const;",
    "",
    "export const productThesis = \"Verified autonomous software delivery\" as const;",
    "",
    "export const deliveryStages = [\"Plan\", \"Execute\", \"Prove\", \"Approve\"] as const;",
    "",
    "export type DeliveryStage = (typeof deliveryStages)[number];",
    "",
    "export function getNextDeliveryStage(stage: DeliveryStage): DeliveryStage | null {",
    "  const index = deliveryStages.indexOf(stage);",
    "  if (index === -1 || index === deliveryStages.length - 1) {",
    "    return null;",
    "  }",
    "  return deliveryStages[index + 1] ?? null;",
    "}",
    "",
    "export function getProductSummary(): string {",
    "  return `${productName}: ${productThesis} — ${deliveryStages.join(\" → \")}`;",
    "}",
    "",
  ].join("\n"),
  "test/index.test.js": [
    "import assert from \"node:assert/strict\";",
    "import test from \"node:test\";",
    "",
    "import {",
    "  deliveryStages,",
    "  getNextDeliveryStage,",
    "  getProductSummary,",
    "  productName,",
    "  productThesis,",
    "} from \"../dist/index.js\";",
    "",
    "test(\"exports the product identity and delivery thesis\", () => {",
    "  assert.equal(productName, \"TrueForge Proof Board\");",
    "  assert.equal(productThesis, \"Verified autonomous software delivery\");",
    "  assert.deepEqual(deliveryStages, [\"Plan\", \"Execute\", \"Prove\", \"Approve\"]);",
    "  assert.equal(",
    "    getProductSummary(),",
    "    \"TrueForge Proof Board: Verified autonomous software delivery — Plan → Execute → Prove → Approve\",",
    "  );",
    "});",
    "",
    "test(\"returns the next delivery stage for every transition\", () => {",
    "  assert.equal(getNextDeliveryStage(\"Plan\"), \"Execute\");",
    "  assert.equal(getNextDeliveryStage(\"Execute\"), \"Prove\");",
    "  assert.equal(getNextDeliveryStage(\"Prove\"), \"Approve\");",
    "  assert.equal(getNextDeliveryStage(\"Approve\"), null);",
    "});",
    "",
  ].join("\n"),
} as const;

export const PRIMARY_VERIFIED_DELIVERY_PATCHES = {
  "src/index.ts": [
    "@@ -6,6 +6,14 @@ export const deliveryStages = [\"Plan\", \"Execute\", \"Prove\", \"Approve\"] as const;",
    " ",
    " export type DeliveryStage = (typeof deliveryStages)[number];",
    " ",
    "+export function getNextDeliveryStage(stage: DeliveryStage): DeliveryStage | null {",
    "+  const index = deliveryStages.indexOf(stage);",
    "+  if (index === -1 || index === deliveryStages.length - 1) {",
    "+    return null;",
    "+  }",
    "+  return deliveryStages[index + 1] ?? null;",
    "+}",
    "+",
    " export function getProductSummary(): string {",
    "   return `${productName}: ${productThesis} — ${deliveryStages.join(\" → \")}`;",
    " }",
  ].join("\n"),
  "test/index.test.js": [
    "@@ -3,6 +3,7 @@ import test from \"node:test\";",
    " import {",
    "   deliveryStages,",
    "+  getNextDeliveryStage,",
    "   getProductSummary,",
    "   productName,",
    "   productThesis,",
    "@@ -17,3 +18,10 @@ test(\"exports the product identity and delivery thesis\", () => {",
    "     \"TrueForge Proof Board: Verified autonomous software delivery — Plan → Execute → Prove → Approve\",",
    "   );",
    " });",
    "+",
    "+test(\"returns the next delivery stage for every transition\", () => {",
    "+  assert.equal(getNextDeliveryStage(\"Plan\"), \"Execute\");",
    "+  assert.equal(getNextDeliveryStage(\"Execute\"), \"Prove\");",
    "+  assert.equal(getNextDeliveryStage(\"Prove\"), \"Approve\");",
    "+  assert.equal(getNextDeliveryStage(\"Approve\"), null);",
    "+});",
  ].join("\n"),
} as const;
